[package]
name = "saf"
version = "0.1.0"
edition = "2021"
default-run = "interpreter"

[lib]
name = "saf"
path = "src/lib.rs"

[[bin]]
name = "interpreter"
path = "interpreter/main.rs"

[dependencies]
