[package]
name = "saf"
version = "0.2.0"
edition = "2021"
default-run = "compiler"

[lib]
name = "saf"
path = "src/lib.rs"

[[bin]]
name = "interpreter"
path = "interpreter/main.rs"

[[bin]]
name = "compiler"
path = "compiler/main.rs"

[dependencies]
