#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 77
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 55
#define ALIAS_COUNT 1
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 8

enum ts_symbol_identifiers {
  anon_sym_POUND = 1,
  aux_sym_comment_token1 = 2,
  anon_sym_SEMI = 3,
  anon_sym_EQ = 4,
  anon_sym_LPAREN = 5,
  anon_sym_RPAREN = 6,
  anon_sym_COMMA = 7,
  anon_sym_QMARK = 8,
  anon_sym_COLON = 9,
  anon_sym_PIPE = 10,
  anon_sym_AMP = 11,
  anon_sym_LT = 12,
  anon_sym_GT = 13,
  anon_sym_BANG_EQ = 14,
  anon_sym_EQ_EQ = 15,
  anon_sym_PLUS = 16,
  anon_sym_DASH = 17,
  anon_sym_STAR = 18,
  anon_sym_SLASH = 19,
  anon_sym_BANG = 20,
  anon_sym_true = 21,
  anon_sym_false = 22,
  sym_int = 23,
  anon_sym_DQUOTE = 24,
  aux_sym_string_token1 = 25,
  sym_identifier = 26,
  anon_sym_LBRACK = 27,
  anon_sym_RBRACK = 28,
  anon_sym_fn = 29,
  anon_sym_LBRACE = 30,
  anon_sym_RBRACE = 31,
  sym_source_file = 32,
  sym_comment = 33,
  sym__statement = 34,
  sym_statement = 35,
  sym__exp = 36,
  sym_call = 37,
  sym_args = 38,
  sym_cond = 39,
  sym_binexp = 40,
  sym_paren = 41,
  sym_unexp = 42,
  sym_unop = 43,
  sym__value = 44,
  sym_bool = 45,
  sym_string = 46,
  sym_array = 47,
  sym_func = 48,
  sym_params = 49,
  sym_def = 50,
  aux_sym_source_file_repeat1 = 51,
  aux_sym_args_repeat1 = 52,
  aux_sym_array_repeat1 = 53,
  aux_sym_params_repeat1 = 54,
  alias_sym_exp = 55,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_SEMI] = ";",
  [anon_sym_EQ] = "=",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_QMARK] = "\?",
  [anon_sym_COLON] = ":",
  [anon_sym_PIPE] = "binop",
  [anon_sym_AMP] = "binop",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = "binop",
  [anon_sym_BANG_EQ] = "binop",
  [anon_sym_EQ_EQ] = "binop",
  [anon_sym_PLUS] = "binop",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "binop",
  [anon_sym_SLASH] = "binop",
  [anon_sym_BANG] = "!",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_int] = "int",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_identifier] = "identifier",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_fn] = "fn",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_source_file] = "source_file",
  [sym_comment] = "comment",
  [sym__statement] = "_statement",
  [sym_statement] = "statement",
  [sym__exp] = "_exp",
  [sym_call] = "call",
  [sym_args] = "args",
  [sym_cond] = "cond",
  [sym_binexp] = "binexp",
  [sym_paren] = "paren",
  [sym_unexp] = "unexp",
  [sym_unop] = "unop",
  [sym__value] = "_value",
  [sym_bool] = "bool",
  [sym_string] = "string",
  [sym_array] = "array",
  [sym_func] = "func",
  [sym_params] = "params",
  [sym_def] = "def",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_args_repeat1] = "args_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_params_repeat1] = "params_repeat1",
  [alias_sym_exp] = "exp",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_AMP] = anon_sym_PIPE,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_PIPE,
  [anon_sym_BANG_EQ] = anon_sym_PIPE,
  [anon_sym_EQ_EQ] = anon_sym_PIPE,
  [anon_sym_PLUS] = anon_sym_PIPE,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_PIPE,
  [anon_sym_SLASH] = anon_sym_PIPE,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_int] = sym_int,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_identifier] = sym_identifier,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_source_file] = sym_source_file,
  [sym_comment] = sym_comment,
  [sym__statement] = sym__statement,
  [sym_statement] = sym_statement,
  [sym__exp] = sym__exp,
  [sym_call] = sym_call,
  [sym_args] = sym_args,
  [sym_cond] = sym_cond,
  [sym_binexp] = sym_binexp,
  [sym_paren] = sym_paren,
  [sym_unexp] = sym_unexp,
  [sym_unop] = sym_unop,
  [sym__value] = sym__value,
  [sym_bool] = sym_bool,
  [sym_string] = sym_string,
  [sym_array] = sym_array,
  [sym_func] = sym_func,
  [sym_params] = sym_params,
  [sym_def] = sym_def,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_args_repeat1] = aux_sym_args_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_params_repeat1] = aux_sym_params_repeat1,
  [alias_sym_exp] = alias_sym_exp,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__exp] = {
    .visible = false,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_args] = {
    .visible = true,
    .named = true,
  },
  [sym_cond] = {
    .visible = true,
    .named = true,
  },
  [sym_binexp] = {
    .visible = true,
    .named = true,
  },
  [sym_paren] = {
    .visible = true,
    .named = true,
  },
  [sym_unexp] = {
    .visible = true,
    .named = true,
  },
  [sym_unop] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_func] = {
    .visible = true,
    .named = true,
  },
  [sym_params] = {
    .visible = true,
    .named = true,
  },
  [sym_def] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_args_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_params_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_exp] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_arguments = 1,
  field_definition = 2,
  field_expression = 3,
  field_name = 4,
  field_parameters = 5,
  field_value = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_definition] = "definition",
  [field_expression] = "expression",
  [field_name] = "name",
  [field_parameters] = "parameters",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 2},
  [3] = {.index = 2, .length = 1},
  [5] = {.index = 3, .length = 1},
  [6] = {.index = 4, .length = 2},
  [7] = {.index = 6, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
    {field_value, 2},
  [2] =
    {field_expression, 0},
  [3] =
    {field_definition, 3},
  [4] =
    {field_arguments, 2},
    {field_expression, 0},
  [6] =
    {field_definition, 4},
    {field_parameters, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_exp,
  },
  [4] = {
    [1] = anon_sym_PIPE,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym__exp, 2,
    sym__exp,
    alias_sym_exp,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '!', 39,
        '"', 43,
        '#', 16,
        '&', 29,
        '(', 23,
        ')', 24,
        '*', 36,
        '+', 34,
        ',', 25,
        '-', 35,
        '/', 37,
        ':', 27,
        ';', 21,
        '<', 30,
        '=', 22,
        '>', 31,
        '?', 26,
        '[', 56,
      );
      if (lookahead == '\\') SKIP(11);
      if (lookahead == ']') ADVANCE(57);
      if (lookahead == 'f') ADVANCE(48);
      if (lookahead == 't') ADVANCE(52);
      if (lookahead == '{') ADVANCE(59);
      if (lookahead == '|') ADVANCE(28);
      if (lookahead == '}') ADVANCE(60);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(7);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(7);
      if (lookahead == '\r') SKIP(1);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead == '\r') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead == '#') ADVANCE(17);
      if (lookahead == '\\') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(19);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      ADVANCE_MAP(
        '!', 9,
        '#', 16,
        '&', 29,
        '(', 23,
        ')', 24,
        '*', 36,
        '+', 34,
        ',', 25,
        '-', 35,
        '/', 37,
        ':', 27,
        ';', 21,
        '<', 30,
        '=', 22,
        '>', 31,
        '?', 26,
      );
      if (lookahead == '\\') SKIP(2);
      if (lookahead == ']') ADVANCE(57);
      if (lookahead == '|') ADVANCE(28);
      if (lookahead == '}') ADVANCE(60);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 8:
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '\\') ADVANCE(44);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#') ADVANCE(47);
      END_STATE();
    case 9:
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 10:
      if (eof) ADVANCE(15);
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 11:
      if (eof) ADVANCE(15);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\r') SKIP(10);
      END_STATE();
    case 12:
      if (eof) ADVANCE(15);
      if (lookahead == '\n') SKIP(14);
      END_STATE();
    case 13:
      if (eof) ADVANCE(15);
      if (lookahead == '\n') SKIP(14);
      if (lookahead == '\r') SKIP(12);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '!', 38,
        '"', 43,
        '#', 16,
        '(', 23,
        ')', 24,
        '-', 35,
        '<', 30,
        '[', 56,
      );
      if (lookahead == '\\') SKIP(13);
      if (lookahead == 'f') ADVANCE(48);
      if (lookahead == 't') ADVANCE(52);
      if (lookahead == '{') ADVANCE(59);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '\n') ADVANCE(19);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(47);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead == '#') ADVANCE(17);
      if (lookahead == '\\') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(33);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_int);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\n') ADVANCE(46);
      if (lookahead == '\r') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(47);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\n') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(47);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '\\') ADVANCE(44);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#') ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(51);
      if (lookahead == 'n') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 14},
  [2] = {.lex_state = 14},
  [3] = {.lex_state = 14},
  [4] = {.lex_state = 14},
  [5] = {.lex_state = 14},
  [6] = {.lex_state = 14},
  [7] = {.lex_state = 14},
  [8] = {.lex_state = 14},
  [9] = {.lex_state = 14},
  [10] = {.lex_state = 14},
  [11] = {.lex_state = 14},
  [12] = {.lex_state = 14},
  [13] = {.lex_state = 14},
  [14] = {.lex_state = 14},
  [15] = {.lex_state = 14},
  [16] = {.lex_state = 14},
  [17] = {.lex_state = 14},
  [18] = {.lex_state = 14},
  [19] = {.lex_state = 7},
  [20] = {.lex_state = 7},
  [21] = {.lex_state = 7},
  [22] = {.lex_state = 7},
  [23] = {.lex_state = 7},
  [24] = {.lex_state = 7},
  [25] = {.lex_state = 7},
  [26] = {.lex_state = 7},
  [27] = {.lex_state = 7},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 7},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 7},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 7},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 7},
  [37] = {.lex_state = 7},
  [38] = {.lex_state = 7},
  [39] = {.lex_state = 7},
  [40] = {.lex_state = 7},
  [41] = {.lex_state = 7},
  [42] = {.lex_state = 7},
  [43] = {.lex_state = 7},
  [44] = {.lex_state = 7},
  [45] = {.lex_state = 7},
  [46] = {.lex_state = 7},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 7},
  [49] = {.lex_state = 7},
  [50] = {.lex_state = 14},
  [51] = {.lex_state = 14},
  [52] = {.lex_state = 14},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 14},
  [55] = {.lex_state = 14},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 7},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 7},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 4},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 8},
  [75] = {.lex_state = 0},
  [76] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_int] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(72),
    [sym_comment] = STATE(1),
    [sym__statement] = STATE(51),
    [sym_statement] = STATE(70),
    [sym__exp] = STATE(48),
    [sym_call] = STATE(21),
    [sym_cond] = STATE(21),
    [sym_binexp] = STATE(21),
    [sym_paren] = STATE(21),
    [sym_unexp] = STATE(21),
    [sym_unop] = STATE(10),
    [sym__value] = STATE(21),
    [sym_bool] = STATE(26),
    [sym_string] = STATE(26),
    [sym_array] = STATE(26),
    [sym_func] = STATE(26),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_int] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_fn] = ACTIONS(23),
  },
  [2] = {
    [sym_comment] = STATE(2),
    [sym__statement] = STATE(51),
    [sym_statement] = STATE(70),
    [sym__exp] = STATE(48),
    [sym_call] = STATE(21),
    [sym_cond] = STATE(21),
    [sym_binexp] = STATE(21),
    [sym_paren] = STATE(21),
    [sym_unexp] = STATE(21),
    [sym_unop] = STATE(10),
    [sym__value] = STATE(21),
    [sym_bool] = STATE(26),
    [sym_string] = STATE(26),
    [sym_array] = STATE(26),
    [sym_func] = STATE(26),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(25),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(30),
    [anon_sym_DASH] = ACTIONS(33),
    [anon_sym_BANG] = ACTIONS(30),
    [anon_sym_true] = ACTIONS(36),
    [anon_sym_false] = ACTIONS(36),
    [sym_int] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(42),
    [sym_identifier] = ACTIONS(45),
    [anon_sym_LBRACK] = ACTIONS(48),
    [anon_sym_fn] = ACTIONS(51),
  },
  [3] = {
    [sym_comment] = STATE(3),
    [sym__statement] = STATE(51),
    [sym_statement] = STATE(70),
    [sym__exp] = STATE(48),
    [sym_call] = STATE(21),
    [sym_cond] = STATE(21),
    [sym_binexp] = STATE(21),
    [sym_paren] = STATE(21),
    [sym_unexp] = STATE(21),
    [sym_unop] = STATE(10),
    [sym__value] = STATE(21),
    [sym_bool] = STATE(26),
    [sym_string] = STATE(26),
    [sym_array] = STATE(26),
    [sym_func] = STATE(26),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(54),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_int] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_fn] = ACTIONS(23),
  },
  [4] = {
    [sym_comment] = STATE(4),
    [sym__statement] = STATE(51),
    [sym_statement] = STATE(70),
    [sym__exp] = STATE(42),
    [sym_call] = STATE(21),
    [sym_cond] = STATE(21),
    [sym_binexp] = STATE(21),
    [sym_paren] = STATE(21),
    [sym_unexp] = STATE(21),
    [sym_unop] = STATE(10),
    [sym__value] = STATE(21),
    [sym_bool] = STATE(26),
    [sym_string] = STATE(26),
    [sym_array] = STATE(26),
    [sym_func] = STATE(26),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_int] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_fn] = ACTIONS(23),
  },
  [5] = {
    [sym_comment] = STATE(5),
    [sym__statement] = STATE(51),
    [sym_statement] = STATE(70),
    [sym__exp] = STATE(44),
    [sym_call] = STATE(21),
    [sym_cond] = STATE(21),
    [sym_binexp] = STATE(21),
    [sym_paren] = STATE(21),
    [sym_unexp] = STATE(21),
    [sym_unop] = STATE(10),
    [sym__value] = STATE(21),
    [sym_bool] = STATE(26),
    [sym_string] = STATE(26),
    [sym_array] = STATE(26),
    [sym_func] = STATE(26),
    [aux_sym_source_file_repeat1] = STATE(4),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_int] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_fn] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 17,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      sym_int,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_fn,
    ACTIONS(56), 1,
      sym_identifier,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    STATE(6), 1,
      sym_comment,
    STATE(10), 1,
      sym_unop,
    STATE(24), 1,
      sym_def,
    STATE(25), 1,
      sym__exp,
    ACTIONS(9), 2,
      anon_sym_LT,
      anon_sym_BANG,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(26), 4,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
    STATE(21), 6,
      sym_call,
      sym_cond,
      sym_binexp,
      sym_paren,
      sym_unexp,
      sym__value,
  [62] = 17,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      sym_int,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_fn,
    ACTIONS(56), 1,
      sym_identifier,
    ACTIONS(60), 1,
      anon_sym_RPAREN,
    STATE(7), 1,
      sym_comment,
    STATE(10), 1,
      sym_unop,
    STATE(41), 1,
      sym__exp,
    STATE(69), 1,
      sym_args,
    ACTIONS(9), 2,
      anon_sym_LT,
      anon_sym_BANG,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(26), 4,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
    STATE(21), 6,
      sym_call,
      sym_cond,
      sym_binexp,
      sym_paren,
      sym_unexp,
      sym__value,
  [124] = 17,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      sym_int,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_fn,
    ACTIONS(56), 1,
      sym_identifier,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    STATE(8), 1,
      sym_comment,
    STATE(10), 1,
      sym_unop,
    STATE(25), 1,
      sym__exp,
    STATE(31), 1,
      sym_def,
    ACTIONS(9), 2,
      anon_sym_LT,
      anon_sym_BANG,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(26), 4,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
    STATE(21), 6,
      sym_call,
      sym_cond,
      sym_binexp,
      sym_paren,
      sym_unexp,
      sym__value,
  [186] = 15,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      sym_int,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_fn,
    ACTIONS(56), 1,
      sym_identifier,
    STATE(9), 1,
      sym_comment,
    STATE(10), 1,
      sym_unop,
    STATE(20), 1,
      sym__exp,
    ACTIONS(9), 2,
      anon_sym_LT,
      anon_sym_BANG,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(26), 4,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
    STATE(21), 6,
      sym_call,
      sym_cond,
      sym_binexp,
      sym_paren,
      sym_unexp,
      sym__value,
  [242] = 14,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      sym_int,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_fn,
    ACTIONS(56), 1,
      sym_identifier,
    STATE(34), 1,
      sym__exp,
    ACTIONS(9), 2,
      anon_sym_LT,
      anon_sym_BANG,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(10), 2,
      sym_comment,
      sym_unop,
    STATE(26), 4,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
    STATE(21), 6,
      sym_call,
      sym_cond,
      sym_binexp,
      sym_paren,
      sym_unexp,
      sym__value,
  [296] = 15,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      sym_int,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_fn,
    ACTIONS(56), 1,
      sym_identifier,
    STATE(10), 1,
      sym_unop,
    STATE(11), 1,
      sym_comment,
    STATE(45), 1,
      sym__exp,
    ACTIONS(9), 2,
      anon_sym_LT,
      anon_sym_BANG,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(26), 4,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
    STATE(21), 6,
      sym_call,
      sym_cond,
      sym_binexp,
      sym_paren,
      sym_unexp,
      sym__value,
  [352] = 15,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      sym_int,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_fn,
    ACTIONS(56), 1,
      sym_identifier,
    STATE(10), 1,
      sym_unop,
    STATE(12), 1,
      sym_comment,
    STATE(33), 1,
      sym__exp,
    ACTIONS(9), 2,
      anon_sym_LT,
      anon_sym_BANG,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(26), 4,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
    STATE(21), 6,
      sym_call,
      sym_cond,
      sym_binexp,
      sym_paren,
      sym_unexp,
      sym__value,
  [408] = 15,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      sym_int,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_fn,
    ACTIONS(56), 1,
      sym_identifier,
    STATE(10), 1,
      sym_unop,
    STATE(13), 1,
      sym_comment,
    STATE(30), 1,
      sym__exp,
    ACTIONS(9), 2,
      anon_sym_LT,
      anon_sym_BANG,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(26), 4,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
    STATE(21), 6,
      sym_call,
      sym_cond,
      sym_binexp,
      sym_paren,
      sym_unexp,
      sym__value,
  [464] = 15,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      sym_int,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_fn,
    ACTIONS(56), 1,
      sym_identifier,
    STATE(10), 1,
      sym_unop,
    STATE(14), 1,
      sym_comment,
    STATE(32), 1,
      sym__exp,
    ACTIONS(9), 2,
      anon_sym_LT,
      anon_sym_BANG,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(26), 4,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
    STATE(21), 6,
      sym_call,
      sym_cond,
      sym_binexp,
      sym_paren,
      sym_unexp,
      sym__value,
  [520] = 15,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      sym_int,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_fn,
    ACTIONS(56), 1,
      sym_identifier,
    STATE(10), 1,
      sym_unop,
    STATE(15), 1,
      sym_comment,
    STATE(46), 1,
      sym__exp,
    ACTIONS(9), 2,
      anon_sym_LT,
      anon_sym_BANG,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(26), 4,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
    STATE(21), 6,
      sym_call,
      sym_cond,
      sym_binexp,
      sym_paren,
      sym_unexp,
      sym__value,
  [576] = 15,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      sym_int,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_fn,
    ACTIONS(56), 1,
      sym_identifier,
    STATE(10), 1,
      sym_unop,
    STATE(16), 1,
      sym_comment,
    STATE(29), 1,
      sym__exp,
    ACTIONS(9), 2,
      anon_sym_LT,
      anon_sym_BANG,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(26), 4,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
    STATE(21), 6,
      sym_call,
      sym_cond,
      sym_binexp,
      sym_paren,
      sym_unexp,
      sym__value,
  [632] = 15,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      sym_int,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_fn,
    ACTIONS(56), 1,
      sym_identifier,
    STATE(10), 1,
      sym_unop,
    STATE(17), 1,
      sym_comment,
    STATE(43), 1,
      sym__exp,
    ACTIONS(9), 2,
      anon_sym_LT,
      anon_sym_BANG,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(26), 4,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
    STATE(21), 6,
      sym_call,
      sym_cond,
      sym_binexp,
      sym_paren,
      sym_unexp,
      sym__value,
  [688] = 15,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      sym_int,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_fn,
    ACTIONS(56), 1,
      sym_identifier,
    STATE(10), 1,
      sym_unop,
    STATE(18), 1,
      sym_comment,
    STATE(49), 1,
      sym__exp,
    ACTIONS(9), 2,
      anon_sym_LT,
      anon_sym_BANG,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(26), 4,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
    STATE(21), 6,
      sym_call,
      sym_cond,
      sym_binexp,
      sym_paren,
      sym_unexp,
      sym__value,
  [744] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(19), 1,
      sym_comment,
    ACTIONS(62), 18,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [771] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    STATE(20), 1,
      sym_comment,
    ACTIONS(64), 17,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [800] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(21), 1,
      sym_comment,
    ACTIONS(68), 18,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [827] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(22), 1,
      sym_comment,
    ACTIONS(70), 18,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [854] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(23), 1,
      sym_comment,
    ACTIONS(72), 18,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [881] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(24), 1,
      sym_comment,
    ACTIONS(74), 18,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [908] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(78), 1,
      anon_sym_QMARK,
    STATE(25), 1,
      sym_comment,
    ACTIONS(80), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(84), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(86), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(82), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(76), 6,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [947] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(26), 1,
      sym_comment,
    ACTIONS(88), 18,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [974] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(27), 1,
      sym_comment,
    ACTIONS(90), 18,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1001] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(28), 1,
      sym_comment,
    ACTIONS(92), 18,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1028] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    STATE(29), 1,
      sym_comment,
    ACTIONS(80), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(84), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(86), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(82), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(94), 7,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1065] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    STATE(30), 1,
      sym_comment,
    ACTIONS(84), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(86), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(64), 13,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1098] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(31), 1,
      sym_comment,
    ACTIONS(96), 18,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1125] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    STATE(32), 1,
      sym_comment,
    ACTIONS(84), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(86), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(82), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(64), 9,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1160] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    STATE(33), 1,
      sym_comment,
    ACTIONS(86), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(64), 15,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1191] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(78), 1,
      anon_sym_QMARK,
    STATE(34), 1,
      sym_comment,
    ACTIONS(80), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(84), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(86), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(82), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(98), 6,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1230] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(35), 1,
      sym_comment,
    ACTIONS(100), 18,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1257] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(36), 1,
      sym_comment,
    ACTIONS(102), 18,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1284] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(37), 1,
      sym_comment,
    ACTIONS(104), 18,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1311] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(38), 1,
      sym_comment,
    ACTIONS(106), 18,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1338] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(39), 1,
      sym_comment,
    ACTIONS(108), 18,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1365] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(110), 1,
      anon_sym_EQ,
    STATE(40), 1,
      sym_comment,
    ACTIONS(88), 14,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_QMARK,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACE,
  [1391] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(78), 1,
      anon_sym_QMARK,
    ACTIONS(112), 1,
      anon_sym_RPAREN,
    ACTIONS(114), 1,
      anon_sym_COMMA,
    STATE(41), 1,
      sym_comment,
    STATE(60), 1,
      aux_sym_args_repeat1,
    ACTIONS(80), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(84), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(86), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(82), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [1431] = 10,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(78), 1,
      anon_sym_QMARK,
    ACTIONS(116), 1,
      anon_sym_SEMI,
    ACTIONS(118), 1,
      anon_sym_RBRACE,
    STATE(42), 1,
      sym_comment,
    ACTIONS(80), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(84), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(86), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(82), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [1468] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(78), 1,
      anon_sym_QMARK,
    STATE(43), 1,
      sym_comment,
    ACTIONS(80), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(84), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(86), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(120), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(82), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [1503] = 10,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(78), 1,
      anon_sym_QMARK,
    ACTIONS(116), 1,
      anon_sym_SEMI,
    ACTIONS(122), 1,
      anon_sym_RBRACE,
    STATE(44), 1,
      sym_comment,
    ACTIONS(80), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(84), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(86), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(82), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [1540] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(78), 1,
      anon_sym_QMARK,
    ACTIONS(124), 1,
      anon_sym_RPAREN,
    STATE(45), 1,
      sym_comment,
    ACTIONS(80), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(84), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(86), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(82), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [1574] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(78), 1,
      anon_sym_QMARK,
    ACTIONS(126), 1,
      anon_sym_COLON,
    STATE(46), 1,
      sym_comment,
    ACTIONS(80), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(84), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(86), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(82), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [1608] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(15), 1,
      sym_int,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_fn,
    ACTIONS(56), 1,
      sym_identifier,
    ACTIONS(128), 1,
      anon_sym_RBRACK,
    STATE(47), 1,
      sym_comment,
    STATE(59), 1,
      sym__value,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(26), 4,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
  [1646] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(78), 1,
      anon_sym_QMARK,
    ACTIONS(116), 1,
      anon_sym_SEMI,
    STATE(48), 1,
      sym_comment,
    ACTIONS(80), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(84), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(86), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(82), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [1680] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(78), 1,
      anon_sym_QMARK,
    ACTIONS(130), 1,
      anon_sym_SEMI,
    STATE(49), 1,
      sym_comment,
    ACTIONS(80), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(84), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(86), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(82), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [1714] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(50), 1,
      sym_comment,
    ACTIONS(134), 4,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_fn,
    ACTIONS(132), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LT,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_int,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [1737] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(51), 1,
      sym_comment,
    ACTIONS(138), 4,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_fn,
    ACTIONS(136), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LT,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_int,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [1760] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(52), 1,
      sym_comment,
    ACTIONS(142), 4,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_fn,
    ACTIONS(140), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LT,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_int,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [1783] = 10,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(15), 1,
      sym_int,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_fn,
    ACTIONS(56), 1,
      sym_identifier,
    STATE(53), 1,
      sym_comment,
    STATE(65), 1,
      sym__value,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(26), 4,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
  [1818] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(54), 1,
      sym_comment,
    ACTIONS(146), 4,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_fn,
    ACTIONS(144), 7,
      anon_sym_LPAREN,
      anon_sym_LT,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_int,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [1840] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(55), 1,
      sym_comment,
    ACTIONS(146), 4,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_fn,
    ACTIONS(144), 7,
      anon_sym_LPAREN,
      anon_sym_LT,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_int,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [1862] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(148), 1,
      anon_sym_RPAREN,
    ACTIONS(150), 1,
      anon_sym_COMMA,
    STATE(56), 1,
      sym_comment,
    STATE(61), 1,
      aux_sym_params_repeat1,
  [1878] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(152), 1,
      anon_sym_COMMA,
    ACTIONS(155), 1,
      anon_sym_RBRACK,
    STATE(57), 2,
      sym_comment,
      aux_sym_array_repeat1,
  [1892] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(157), 1,
      anon_sym_RPAREN,
    ACTIONS(159), 1,
      sym_identifier,
    STATE(58), 1,
      sym_comment,
    STATE(75), 1,
      sym_params,
  [1908] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(161), 1,
      anon_sym_COMMA,
    ACTIONS(163), 1,
      anon_sym_RBRACK,
    STATE(59), 1,
      sym_comment,
    STATE(63), 1,
      aux_sym_array_repeat1,
  [1924] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(114), 1,
      anon_sym_COMMA,
    ACTIONS(165), 1,
      anon_sym_RPAREN,
    STATE(60), 1,
      sym_comment,
    STATE(62), 1,
      aux_sym_args_repeat1,
  [1940] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(167), 1,
      anon_sym_RPAREN,
    ACTIONS(169), 1,
      anon_sym_COMMA,
    STATE(61), 2,
      sym_comment,
      aux_sym_params_repeat1,
  [1954] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(120), 1,
      anon_sym_RPAREN,
    ACTIONS(172), 1,
      anon_sym_COMMA,
    STATE(62), 2,
      sym_comment,
      aux_sym_args_repeat1,
  [1968] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(161), 1,
      anon_sym_COMMA,
    ACTIONS(175), 1,
      anon_sym_RBRACK,
    STATE(57), 1,
      aux_sym_array_repeat1,
    STATE(63), 1,
      sym_comment,
  [1984] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(150), 1,
      anon_sym_COMMA,
    ACTIONS(177), 1,
      anon_sym_RPAREN,
    STATE(56), 1,
      aux_sym_params_repeat1,
    STATE(64), 1,
      sym_comment,
  [2000] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(65), 1,
      sym_comment,
    ACTIONS(155), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2011] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(66), 1,
      sym_comment,
    ACTIONS(167), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [2022] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(179), 1,
      sym_identifier,
    STATE(67), 1,
      sym_comment,
  [2032] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(181), 1,
      anon_sym_DQUOTE,
    STATE(68), 1,
      sym_comment,
  [2042] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(183), 1,
      anon_sym_RPAREN,
    STATE(69), 1,
      sym_comment,
  [2052] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(185), 1,
      anon_sym_SEMI,
    STATE(70), 1,
      sym_comment,
  [2062] = 3,
    ACTIONS(187), 1,
      anon_sym_POUND,
    ACTIONS(189), 1,
      aux_sym_comment_token1,
    STATE(71), 1,
      sym_comment,
  [2072] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(191), 1,
      ts_builtin_sym_end,
    STATE(72), 1,
      sym_comment,
  [2082] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(193), 1,
      anon_sym_LPAREN,
    STATE(73), 1,
      sym_comment,
  [2092] = 3,
    ACTIONS(187), 1,
      anon_sym_POUND,
    ACTIONS(195), 1,
      aux_sym_string_token1,
    STATE(74), 1,
      sym_comment,
  [2102] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(197), 1,
      anon_sym_RPAREN,
    STATE(75), 1,
      sym_comment,
  [2112] = 1,
    ACTIONS(199), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 62,
  [SMALL_STATE(8)] = 124,
  [SMALL_STATE(9)] = 186,
  [SMALL_STATE(10)] = 242,
  [SMALL_STATE(11)] = 296,
  [SMALL_STATE(12)] = 352,
  [SMALL_STATE(13)] = 408,
  [SMALL_STATE(14)] = 464,
  [SMALL_STATE(15)] = 520,
  [SMALL_STATE(16)] = 576,
  [SMALL_STATE(17)] = 632,
  [SMALL_STATE(18)] = 688,
  [SMALL_STATE(19)] = 744,
  [SMALL_STATE(20)] = 771,
  [SMALL_STATE(21)] = 800,
  [SMALL_STATE(22)] = 827,
  [SMALL_STATE(23)] = 854,
  [SMALL_STATE(24)] = 881,
  [SMALL_STATE(25)] = 908,
  [SMALL_STATE(26)] = 947,
  [SMALL_STATE(27)] = 974,
  [SMALL_STATE(28)] = 1001,
  [SMALL_STATE(29)] = 1028,
  [SMALL_STATE(30)] = 1065,
  [SMALL_STATE(31)] = 1098,
  [SMALL_STATE(32)] = 1125,
  [SMALL_STATE(33)] = 1160,
  [SMALL_STATE(34)] = 1191,
  [SMALL_STATE(35)] = 1230,
  [SMALL_STATE(36)] = 1257,
  [SMALL_STATE(37)] = 1284,
  [SMALL_STATE(38)] = 1311,
  [SMALL_STATE(39)] = 1338,
  [SMALL_STATE(40)] = 1365,
  [SMALL_STATE(41)] = 1391,
  [SMALL_STATE(42)] = 1431,
  [SMALL_STATE(43)] = 1468,
  [SMALL_STATE(44)] = 1503,
  [SMALL_STATE(45)] = 1540,
  [SMALL_STATE(46)] = 1574,
  [SMALL_STATE(47)] = 1608,
  [SMALL_STATE(48)] = 1646,
  [SMALL_STATE(49)] = 1680,
  [SMALL_STATE(50)] = 1714,
  [SMALL_STATE(51)] = 1737,
  [SMALL_STATE(52)] = 1760,
  [SMALL_STATE(53)] = 1783,
  [SMALL_STATE(54)] = 1818,
  [SMALL_STATE(55)] = 1840,
  [SMALL_STATE(56)] = 1862,
  [SMALL_STATE(57)] = 1878,
  [SMALL_STATE(58)] = 1892,
  [SMALL_STATE(59)] = 1908,
  [SMALL_STATE(60)] = 1924,
  [SMALL_STATE(61)] = 1940,
  [SMALL_STATE(62)] = 1954,
  [SMALL_STATE(63)] = 1968,
  [SMALL_STATE(64)] = 1984,
  [SMALL_STATE(65)] = 2000,
  [SMALL_STATE(66)] = 2011,
  [SMALL_STATE(67)] = 2022,
  [SMALL_STATE(68)] = 2032,
  [SMALL_STATE(69)] = 2042,
  [SMALL_STATE(70)] = 2052,
  [SMALL_STATE(71)] = 2062,
  [SMALL_STATE(72)] = 2072,
  [SMALL_STATE(73)] = 2082,
  [SMALL_STATE(74)] = 2092,
  [SMALL_STATE(75)] = 2102,
  [SMALL_STATE(76)] = 2112,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binexp, 3, 0, 4),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exp, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def, 4, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 4, 0, 5),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cond, 5, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 5, 0, 7),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unexp, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, 0, 3),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, 0, 6),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_args, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_args_repeat1, 2, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 3, 0, 2),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 2, 0, 1),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 2, 0, 1),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 2, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unop, 1, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unop, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_args, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2, 0, 0),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [172] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_args_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 1, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [191] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_saf(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
