#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 77
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 64
#define ALIAS_COUNT 1
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 2

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_EQ = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_COMMA = 5,
  anon_sym_QMARK = 6,
  anon_sym_COLON = 7,
  anon_sym_PIPE = 8,
  anon_sym_AMP = 9,
  anon_sym_LT = 10,
  anon_sym_GT = 11,
  anon_sym_BANG_EQ = 12,
  anon_sym_EQ_EQ = 13,
  anon_sym_PLUS = 14,
  anon_sym_DASH = 15,
  anon_sym_STAR = 16,
  anon_sym_SLASH = 17,
  anon_sym_BANG = 18,
  anon_sym_true = 19,
  anon_sym_false = 20,
  sym_int = 21,
  anon_sym_DQUOTE = 22,
  sym__string = 23,
  sym_identifier = 24,
  anon_sym_LBRACK = 25,
  anon_sym_RBRACK = 26,
  anon_sym_fn = 27,
  anon_sym_LBRACE = 28,
  anon_sym_RBRACE = 29,
  sym_source_file = 30,
  sym__statement = 31,
  sym_statement = 32,
  sym__exp = 33,
  sym_call = 34,
  sym_args = 35,
  sym_cond = 36,
  sym_binexp = 37,
  sym__binexp5 = 38,
  sym__binexp15 = 39,
  sym__binexp25 = 40,
  sym__binexp35 = 41,
  sym_binop5 = 42,
  sym_binop15 = 43,
  sym_binop25 = 44,
  sym_binop35 = 45,
  sym_paren = 46,
  sym_unexp = 47,
  sym_unop = 48,
  sym__unop20 = 49,
  sym__unop40 = 50,
  sym__value = 51,
  sym_bool = 52,
  sym_string = 53,
  sym_array = 54,
  sym__vals = 55,
  sym_func = 56,
  sym_params = 57,
  sym_def = 58,
  sym__def_braces = 59,
  aux_sym_source_file_repeat1 = 60,
  aux_sym_args_repeat1 = 61,
  aux_sym__vals_repeat1 = 62,
  aux_sym_params_repeat1 = 63,
  alias_sym_exp = 64,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_EQ] = "=",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_QMARK] = "\?",
  [anon_sym_COLON] = ":",
  [anon_sym_PIPE] = "|",
  [anon_sym_AMP] = "&",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_BANG] = "!",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_int] = "int",
  [anon_sym_DQUOTE] = "\"",
  [sym__string] = "_string",
  [sym_identifier] = "identifier",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_fn] = "fn",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_statement] = "statement",
  [sym__exp] = "_exp",
  [sym_call] = "call",
  [sym_args] = "args",
  [sym_cond] = "cond",
  [sym_binexp] = "binexp",
  [sym__binexp5] = "_binexp5",
  [sym__binexp15] = "_binexp15",
  [sym__binexp25] = "_binexp25",
  [sym__binexp35] = "_binexp35",
  [sym_binop5] = "binop",
  [sym_binop15] = "binop",
  [sym_binop25] = "binop",
  [sym_binop35] = "binop",
  [sym_paren] = "paren",
  [sym_unexp] = "unexp",
  [sym_unop] = "unop",
  [sym__unop20] = "_unop20",
  [sym__unop40] = "_unop40",
  [sym__value] = "_value",
  [sym_bool] = "bool",
  [sym_string] = "string",
  [sym_array] = "array",
  [sym__vals] = "_vals",
  [sym_func] = "func",
  [sym_params] = "params",
  [sym_def] = "def",
  [sym__def_braces] = "_def_braces",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_args_repeat1] = "args_repeat1",
  [aux_sym__vals_repeat1] = "_vals_repeat1",
  [aux_sym_params_repeat1] = "params_repeat1",
  [alias_sym_exp] = "exp",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_int] = sym_int,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym__string] = sym__string,
  [sym_identifier] = sym_identifier,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_statement] = sym_statement,
  [sym__exp] = sym__exp,
  [sym_call] = sym_call,
  [sym_args] = sym_args,
  [sym_cond] = sym_cond,
  [sym_binexp] = sym_binexp,
  [sym__binexp5] = sym__binexp5,
  [sym__binexp15] = sym__binexp15,
  [sym__binexp25] = sym__binexp25,
  [sym__binexp35] = sym__binexp35,
  [sym_binop5] = sym_binop5,
  [sym_binop15] = sym_binop5,
  [sym_binop25] = sym_binop5,
  [sym_binop35] = sym_binop5,
  [sym_paren] = sym_paren,
  [sym_unexp] = sym_unexp,
  [sym_unop] = sym_unop,
  [sym__unop20] = sym__unop20,
  [sym__unop40] = sym__unop40,
  [sym__value] = sym__value,
  [sym_bool] = sym_bool,
  [sym_string] = sym_string,
  [sym_array] = sym_array,
  [sym__vals] = sym__vals,
  [sym_func] = sym_func,
  [sym_params] = sym_params,
  [sym_def] = sym_def,
  [sym__def_braces] = sym__def_braces,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_args_repeat1] = aux_sym_args_repeat1,
  [aux_sym__vals_repeat1] = aux_sym__vals_repeat1,
  [aux_sym_params_repeat1] = aux_sym_params_repeat1,
  [alias_sym_exp] = alias_sym_exp,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__string] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__exp] = {
    .visible = false,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_args] = {
    .visible = true,
    .named = true,
  },
  [sym_cond] = {
    .visible = true,
    .named = true,
  },
  [sym_binexp] = {
    .visible = true,
    .named = true,
  },
  [sym__binexp5] = {
    .visible = false,
    .named = true,
  },
  [sym__binexp15] = {
    .visible = false,
    .named = true,
  },
  [sym__binexp25] = {
    .visible = false,
    .named = true,
  },
  [sym__binexp35] = {
    .visible = false,
    .named = true,
  },
  [sym_binop5] = {
    .visible = true,
    .named = true,
  },
  [sym_binop15] = {
    .visible = true,
    .named = true,
  },
  [sym_binop25] = {
    .visible = true,
    .named = true,
  },
  [sym_binop35] = {
    .visible = true,
    .named = true,
  },
  [sym_paren] = {
    .visible = true,
    .named = true,
  },
  [sym_unexp] = {
    .visible = true,
    .named = true,
  },
  [sym_unop] = {
    .visible = true,
    .named = true,
  },
  [sym__unop20] = {
    .visible = false,
    .named = true,
  },
  [sym__unop40] = {
    .visible = false,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym__vals] = {
    .visible = false,
    .named = true,
  },
  [sym_func] = {
    .visible = true,
    .named = true,
  },
  [sym_params] = {
    .visible = true,
    .named = true,
  },
  [sym_def] = {
    .visible = true,
    .named = true,
  },
  [sym__def_braces] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_args_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__vals_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_params_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_exp] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_exp,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym__exp, 2,
    sym__exp,
    alias_sym_exp,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      ADVANCE_MAP(
        '!', 24,
        '"', 28,
        '&', 14,
        '(', 8,
        ')', 9,
        '*', 21,
        '+', 19,
        ',', 10,
        '-', 20,
        '/', 22,
        ':', 12,
        ';', 6,
        '<', 15,
        '=', 7,
        '>', 16,
        '?', 11,
        '[', 39,
        ']', 40,
        'f', 31,
        't', 35,
        '{', 42,
        '|', 13,
        '}', 43,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 2,
        '&', 14,
        '(', 8,
        ')', 9,
        '*', 21,
        '+', 19,
        ',', 10,
        '-', 20,
        '/', 22,
        ':', 12,
        ';', 6,
        '<', 15,
        '=', 7,
        '>', 16,
        '?', 11,
        ']', 40,
        '|', 13,
        '}', 43,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 2:
      if (lookahead == '=') ADVANCE(17);
      END_STATE();
    case 3:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(30);
      END_STATE();
    case 4:
      if (eof) ADVANCE(5);
      ADVANCE_MAP(
        '!', 23,
        '"', 28,
        '(', 8,
        ')', 9,
        '-', 20,
        '<', 15,
        '[', 39,
        'f', 31,
        't', 35,
        '{', 42,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(18);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(17);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_int);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym__string);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym__string);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(34);
      if (lookahead == 'n') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 4},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 4},
  [51] = {.lex_state = 4},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 4},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 4},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 3},
  [76] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_int] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(69),
    [sym__statement] = STATE(4),
    [sym_statement] = STATE(67),
    [sym__exp] = STATE(42),
    [sym_call] = STATE(35),
    [sym_cond] = STATE(35),
    [sym_binexp] = STATE(35),
    [sym__binexp5] = STATE(36),
    [sym__binexp15] = STATE(36),
    [sym__binexp25] = STATE(36),
    [sym__binexp35] = STATE(36),
    [sym_paren] = STATE(35),
    [sym_unexp] = STATE(35),
    [sym_unop] = STATE(10),
    [sym__unop20] = STATE(52),
    [sym__unop40] = STATE(52),
    [sym__value] = STATE(35),
    [sym_bool] = STATE(35),
    [sym_string] = STATE(35),
    [sym_array] = STATE(35),
    [sym_func] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_BANG] = ACTIONS(7),
    [anon_sym_true] = ACTIONS(9),
    [anon_sym_false] = ACTIONS(9),
    [sym_int] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_fn] = ACTIONS(19),
  },
  [2] = {
    [sym__statement] = STATE(5),
    [sym_statement] = STATE(67),
    [sym__exp] = STATE(33),
    [sym_call] = STATE(35),
    [sym_cond] = STATE(35),
    [sym_binexp] = STATE(35),
    [sym__binexp5] = STATE(36),
    [sym__binexp15] = STATE(36),
    [sym__binexp25] = STATE(36),
    [sym__binexp35] = STATE(36),
    [sym_paren] = STATE(35),
    [sym_unexp] = STATE(35),
    [sym_unop] = STATE(10),
    [sym__unop20] = STATE(52),
    [sym__unop40] = STATE(52),
    [sym__value] = STATE(35),
    [sym_bool] = STATE(35),
    [sym_string] = STATE(35),
    [sym_array] = STATE(35),
    [sym_func] = STATE(35),
    [sym__def_braces] = STATE(71),
    [aux_sym_source_file_repeat1] = STATE(5),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_BANG] = ACTIONS(7),
    [anon_sym_true] = ACTIONS(9),
    [anon_sym_false] = ACTIONS(9),
    [sym_int] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_fn] = ACTIONS(19),
  },
  [3] = {
    [sym__statement] = STATE(3),
    [sym_statement] = STATE(67),
    [sym__exp] = STATE(42),
    [sym_call] = STATE(35),
    [sym_cond] = STATE(35),
    [sym_binexp] = STATE(35),
    [sym__binexp5] = STATE(36),
    [sym__binexp15] = STATE(36),
    [sym__binexp25] = STATE(36),
    [sym__binexp35] = STATE(36),
    [sym_paren] = STATE(35),
    [sym_unexp] = STATE(35),
    [sym_unop] = STATE(10),
    [sym__unop20] = STATE(52),
    [sym__unop40] = STATE(52),
    [sym__value] = STATE(35),
    [sym_bool] = STATE(35),
    [sym_string] = STATE(35),
    [sym_array] = STATE(35),
    [sym_func] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(26),
    [anon_sym_DASH] = ACTIONS(26),
    [anon_sym_BANG] = ACTIONS(26),
    [anon_sym_true] = ACTIONS(29),
    [anon_sym_false] = ACTIONS(29),
    [sym_int] = ACTIONS(32),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [sym_identifier] = ACTIONS(38),
    [anon_sym_LBRACK] = ACTIONS(41),
    [anon_sym_fn] = ACTIONS(44),
  },
  [4] = {
    [sym__statement] = STATE(3),
    [sym_statement] = STATE(67),
    [sym__exp] = STATE(42),
    [sym_call] = STATE(35),
    [sym_cond] = STATE(35),
    [sym_binexp] = STATE(35),
    [sym__binexp5] = STATE(36),
    [sym__binexp15] = STATE(36),
    [sym__binexp25] = STATE(36),
    [sym__binexp35] = STATE(36),
    [sym_paren] = STATE(35),
    [sym_unexp] = STATE(35),
    [sym_unop] = STATE(10),
    [sym__unop20] = STATE(52),
    [sym__unop40] = STATE(52),
    [sym__value] = STATE(35),
    [sym_bool] = STATE(35),
    [sym_string] = STATE(35),
    [sym_array] = STATE(35),
    [sym_func] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(47),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_BANG] = ACTIONS(7),
    [anon_sym_true] = ACTIONS(9),
    [anon_sym_false] = ACTIONS(9),
    [sym_int] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_fn] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_int,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_fn,
    STATE(10), 1,
      sym_unop,
    STATE(29), 1,
      sym__exp,
    STATE(67), 1,
      sym_statement,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(3), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(52), 2,
      sym__unop20,
      sym__unop40,
    ACTIONS(7), 3,
      anon_sym_LT,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(36), 4,
      sym__binexp5,
      sym__binexp15,
      sym__binexp25,
      sym__binexp35,
    STATE(35), 10,
      sym_call,
      sym_cond,
      sym_binexp,
      sym_paren,
      sym_unexp,
      sym__value,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
  [63] = 15,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_int,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(49), 1,
      anon_sym_RPAREN,
    ACTIONS(51), 1,
      sym_identifier,
    STATE(10), 1,
      sym_unop,
    STATE(26), 1,
      sym__exp,
    STATE(72), 1,
      sym_args,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(52), 2,
      sym__unop20,
      sym__unop40,
    ACTIONS(7), 3,
      anon_sym_LT,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(36), 4,
      sym__binexp5,
      sym__binexp15,
      sym__binexp25,
      sym__binexp35,
    STATE(35), 10,
      sym_call,
      sym_cond,
      sym_binexp,
      sym_paren,
      sym_unexp,
      sym__value,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
  [125] = 15,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_int,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(51), 1,
      sym_identifier,
    ACTIONS(53), 1,
      anon_sym_LBRACE,
    STATE(10), 1,
      sym_unop,
    STATE(23), 1,
      sym__exp,
    STATE(34), 1,
      sym_def,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(52), 2,
      sym__unop20,
      sym__unop40,
    ACTIONS(7), 3,
      anon_sym_LT,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(36), 4,
      sym__binexp5,
      sym__binexp15,
      sym__binexp25,
      sym__binexp35,
    STATE(35), 10,
      sym_call,
      sym_cond,
      sym_binexp,
      sym_paren,
      sym_unexp,
      sym__value,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
  [187] = 15,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_int,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(51), 1,
      sym_identifier,
    ACTIONS(53), 1,
      anon_sym_LBRACE,
    STATE(10), 1,
      sym_unop,
    STATE(23), 1,
      sym__exp,
    STATE(32), 1,
      sym_def,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(52), 2,
      sym__unop20,
      sym__unop40,
    ACTIONS(7), 3,
      anon_sym_LT,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(36), 4,
      sym__binexp5,
      sym__binexp15,
      sym__binexp25,
      sym__binexp35,
    STATE(35), 10,
      sym_call,
      sym_cond,
      sym_binexp,
      sym_paren,
      sym_unexp,
      sym__value,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
  [249] = 13,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_int,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(51), 1,
      sym_identifier,
    STATE(10), 1,
      sym_unop,
    STATE(43), 1,
      sym__exp,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(52), 2,
      sym__unop20,
      sym__unop40,
    ACTIONS(7), 3,
      anon_sym_LT,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(36), 4,
      sym__binexp5,
      sym__binexp15,
      sym__binexp25,
      sym__binexp35,
    STATE(35), 10,
      sym_call,
      sym_cond,
      sym_binexp,
      sym_paren,
      sym_unexp,
      sym__value,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
  [305] = 13,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_int,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(51), 1,
      sym_identifier,
    STATE(10), 1,
      sym_unop,
    STATE(24), 1,
      sym__exp,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(52), 2,
      sym__unop20,
      sym__unop40,
    ACTIONS(7), 3,
      anon_sym_LT,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(36), 4,
      sym__binexp5,
      sym__binexp15,
      sym__binexp25,
      sym__binexp35,
    STATE(35), 10,
      sym_call,
      sym_cond,
      sym_binexp,
      sym_paren,
      sym_unexp,
      sym__value,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
  [361] = 13,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_int,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(51), 1,
      sym_identifier,
    STATE(10), 1,
      sym_unop,
    STATE(45), 1,
      sym__exp,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(52), 2,
      sym__unop20,
      sym__unop40,
    ACTIONS(7), 3,
      anon_sym_LT,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(36), 4,
      sym__binexp5,
      sym__binexp15,
      sym__binexp25,
      sym__binexp35,
    STATE(35), 10,
      sym_call,
      sym_cond,
      sym_binexp,
      sym_paren,
      sym_unexp,
      sym__value,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
  [417] = 13,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_int,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(51), 1,
      sym_identifier,
    STATE(10), 1,
      sym_unop,
    STATE(20), 1,
      sym__exp,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(52), 2,
      sym__unop20,
      sym__unop40,
    ACTIONS(7), 3,
      anon_sym_LT,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(36), 4,
      sym__binexp5,
      sym__binexp15,
      sym__binexp25,
      sym__binexp35,
    STATE(35), 10,
      sym_call,
      sym_cond,
      sym_binexp,
      sym_paren,
      sym_unexp,
      sym__value,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
  [473] = 13,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_int,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(51), 1,
      sym_identifier,
    STATE(10), 1,
      sym_unop,
    STATE(31), 1,
      sym__exp,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(52), 2,
      sym__unop20,
      sym__unop40,
    ACTIONS(7), 3,
      anon_sym_LT,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(36), 4,
      sym__binexp5,
      sym__binexp15,
      sym__binexp25,
      sym__binexp35,
    STATE(35), 10,
      sym_call,
      sym_cond,
      sym_binexp,
      sym_paren,
      sym_unexp,
      sym__value,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
  [529] = 13,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_int,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(51), 1,
      sym_identifier,
    STATE(10), 1,
      sym_unop,
    STATE(19), 1,
      sym__exp,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(52), 2,
      sym__unop20,
      sym__unop40,
    ACTIONS(7), 3,
      anon_sym_LT,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(36), 4,
      sym__binexp5,
      sym__binexp15,
      sym__binexp25,
      sym__binexp35,
    STATE(35), 10,
      sym_call,
      sym_cond,
      sym_binexp,
      sym_paren,
      sym_unexp,
      sym__value,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
  [585] = 13,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_int,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(51), 1,
      sym_identifier,
    STATE(10), 1,
      sym_unop,
    STATE(25), 1,
      sym__exp,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(52), 2,
      sym__unop20,
      sym__unop40,
    ACTIONS(7), 3,
      anon_sym_LT,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(36), 4,
      sym__binexp5,
      sym__binexp15,
      sym__binexp25,
      sym__binexp35,
    STATE(35), 10,
      sym_call,
      sym_cond,
      sym_binexp,
      sym_paren,
      sym_unexp,
      sym__value,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
  [641] = 13,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_int,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(51), 1,
      sym_identifier,
    STATE(10), 1,
      sym_unop,
    STATE(22), 1,
      sym__exp,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(52), 2,
      sym__unop20,
      sym__unop40,
    ACTIONS(7), 3,
      anon_sym_LT,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(36), 4,
      sym__binexp5,
      sym__binexp15,
      sym__binexp25,
      sym__binexp35,
    STATE(35), 10,
      sym_call,
      sym_cond,
      sym_binexp,
      sym_paren,
      sym_unexp,
      sym__value,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
  [697] = 13,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_int,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(51), 1,
      sym_identifier,
    STATE(10), 1,
      sym_unop,
    STATE(21), 1,
      sym__exp,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(52), 2,
      sym__unop20,
      sym__unop40,
    ACTIONS(7), 3,
      anon_sym_LT,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(36), 4,
      sym__binexp5,
      sym__binexp15,
      sym__binexp25,
      sym__binexp35,
    STATE(35), 10,
      sym_call,
      sym_cond,
      sym_binexp,
      sym_paren,
      sym_unexp,
      sym__value,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
  [753] = 13,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_int,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(51), 1,
      sym_identifier,
    STATE(10), 1,
      sym_unop,
    STATE(44), 1,
      sym__exp,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(52), 2,
      sym__unop20,
      sym__unop40,
    ACTIONS(7), 3,
      anon_sym_LT,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(36), 4,
      sym__binexp5,
      sym__binexp15,
      sym__binexp25,
      sym__binexp35,
    STATE(35), 10,
      sym_call,
      sym_cond,
      sym_binexp,
      sym_paren,
      sym_unexp,
      sym__value,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
  [809] = 6,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    STATE(12), 1,
      sym_binop25,
    STATE(14), 1,
      sym_binop35,
    STATE(16), 1,
      sym_binop5,
    STATE(17), 1,
      sym_binop15,
    ACTIONS(55), 17,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [844] = 7,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    STATE(12), 1,
      sym_binop25,
    STATE(14), 1,
      sym_binop35,
    STATE(16), 1,
      sym_binop5,
    STATE(17), 1,
      sym_binop15,
    ACTIONS(61), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(59), 15,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [881] = 8,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    STATE(12), 1,
      sym_binop25,
    STATE(14), 1,
      sym_binop35,
    STATE(16), 1,
      sym_binop5,
    STATE(17), 1,
      sym_binop15,
    ACTIONS(61), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(65), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(63), 13,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [920] = 9,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    STATE(12), 1,
      sym_binop25,
    STATE(14), 1,
      sym_binop35,
    STATE(16), 1,
      sym_binop5,
    STATE(17), 1,
      sym_binop15,
    ACTIONS(61), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(65), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(69), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(67), 9,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [961] = 11,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(73), 1,
      anon_sym_QMARK,
    STATE(12), 1,
      sym_binop25,
    STATE(14), 1,
      sym_binop35,
    STATE(16), 1,
      sym_binop5,
    STATE(17), 1,
      sym_binop15,
    ACTIONS(61), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(65), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(75), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(69), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(71), 6,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1006] = 11,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(73), 1,
      anon_sym_QMARK,
    STATE(12), 1,
      sym_binop25,
    STATE(14), 1,
      sym_binop35,
    STATE(16), 1,
      sym_binop5,
    STATE(17), 1,
      sym_binop15,
    ACTIONS(61), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(65), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(75), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(69), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(77), 6,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1051] = 10,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    STATE(12), 1,
      sym_binop25,
    STATE(14), 1,
      sym_binop35,
    STATE(16), 1,
      sym_binop5,
    STATE(17), 1,
      sym_binop15,
    ACTIONS(61), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(65), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(75), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(69), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(79), 7,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1094] = 13,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(73), 1,
      anon_sym_QMARK,
    ACTIONS(81), 1,
      anon_sym_RPAREN,
    ACTIONS(83), 1,
      anon_sym_COMMA,
    STATE(12), 1,
      sym_binop25,
    STATE(14), 1,
      sym_binop35,
    STATE(16), 1,
      sym_binop5,
    STATE(17), 1,
      sym_binop15,
    STATE(59), 1,
      aux_sym_args_repeat1,
    ACTIONS(61), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(65), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(75), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(69), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [1140] = 1,
    ACTIONS(85), 18,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1161] = 1,
    ACTIONS(87), 18,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1182] = 12,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(73), 1,
      anon_sym_QMARK,
    ACTIONS(89), 1,
      anon_sym_SEMI,
    ACTIONS(91), 1,
      anon_sym_RBRACE,
    STATE(12), 1,
      sym_binop25,
    STATE(14), 1,
      sym_binop35,
    STATE(16), 1,
      sym_binop5,
    STATE(17), 1,
      sym_binop15,
    ACTIONS(61), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(65), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(75), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(69), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [1225] = 1,
    ACTIONS(93), 18,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1246] = 11,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(73), 1,
      anon_sym_QMARK,
    STATE(12), 1,
      sym_binop25,
    STATE(14), 1,
      sym_binop35,
    STATE(16), 1,
      sym_binop5,
    STATE(17), 1,
      sym_binop15,
    ACTIONS(61), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(65), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(75), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(95), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(69), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [1287] = 1,
    ACTIONS(97), 18,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1308] = 12,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(73), 1,
      anon_sym_QMARK,
    ACTIONS(89), 1,
      anon_sym_SEMI,
    ACTIONS(99), 1,
      anon_sym_RBRACE,
    STATE(12), 1,
      sym_binop25,
    STATE(14), 1,
      sym_binop35,
    STATE(16), 1,
      sym_binop5,
    STATE(17), 1,
      sym_binop15,
    ACTIONS(61), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(65), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(75), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(69), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [1351] = 1,
    ACTIONS(101), 18,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1372] = 1,
    ACTIONS(103), 18,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1393] = 1,
    ACTIONS(105), 18,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1414] = 1,
    ACTIONS(107), 18,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1435] = 1,
    ACTIONS(109), 18,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1456] = 1,
    ACTIONS(111), 18,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1477] = 1,
    ACTIONS(113), 18,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1498] = 1,
    ACTIONS(115), 18,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1519] = 11,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(73), 1,
      anon_sym_QMARK,
    ACTIONS(89), 1,
      anon_sym_SEMI,
    STATE(12), 1,
      sym_binop25,
    STATE(14), 1,
      sym_binop35,
    STATE(16), 1,
      sym_binop5,
    STATE(17), 1,
      sym_binop15,
    ACTIONS(61), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(65), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(75), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(69), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [1559] = 11,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(73), 1,
      anon_sym_QMARK,
    ACTIONS(117), 1,
      anon_sym_SEMI,
    STATE(12), 1,
      sym_binop25,
    STATE(14), 1,
      sym_binop35,
    STATE(16), 1,
      sym_binop5,
    STATE(17), 1,
      sym_binop15,
    ACTIONS(61), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(65), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(75), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(69), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [1599] = 11,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(73), 1,
      anon_sym_QMARK,
    ACTIONS(119), 1,
      anon_sym_COLON,
    STATE(12), 1,
      sym_binop25,
    STATE(14), 1,
      sym_binop35,
    STATE(16), 1,
      sym_binop5,
    STATE(17), 1,
      sym_binop15,
    ACTIONS(61), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(65), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(75), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(69), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [1639] = 11,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(73), 1,
      anon_sym_QMARK,
    ACTIONS(121), 1,
      anon_sym_RPAREN,
    STATE(12), 1,
      sym_binop25,
    STATE(14), 1,
      sym_binop35,
    STATE(16), 1,
      sym_binop5,
    STATE(17), 1,
      sym_binop15,
    ACTIONS(61), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(65), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(75), 2,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(69), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
  [1679] = 2,
    ACTIONS(125), 1,
      anon_sym_EQ,
    ACTIONS(123), 14,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_QMARK,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RBRACE,
  [1699] = 9,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(127), 1,
      sym_int,
    ACTIONS(129), 1,
      sym_identifier,
    ACTIONS(131), 1,
      anon_sym_RBRACK,
    STATE(76), 1,
      sym__vals,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(56), 5,
      sym__value,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
  [1732] = 7,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(133), 1,
      sym_int,
    ACTIONS(135), 1,
      sym_identifier,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(65), 5,
      sym__value,
      sym_bool,
      sym_string,
      sym_array,
      sym_func,
  [1759] = 2,
    ACTIONS(139), 4,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_fn,
    ACTIONS(137), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LT,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_int,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [1776] = 2,
    ACTIONS(143), 4,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_fn,
    ACTIONS(141), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LT,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_int,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [1793] = 2,
    ACTIONS(147), 4,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_fn,
    ACTIONS(145), 7,
      anon_sym_LPAREN,
      anon_sym_LT,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_int,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [1809] = 2,
    ACTIONS(151), 4,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_fn,
    ACTIONS(149), 7,
      anon_sym_LPAREN,
      anon_sym_LT,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_int,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [1825] = 2,
    ACTIONS(155), 4,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_fn,
    ACTIONS(153), 7,
      anon_sym_LPAREN,
      anon_sym_LT,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_int,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [1841] = 2,
    ACTIONS(159), 4,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_fn,
    ACTIONS(157), 7,
      anon_sym_LPAREN,
      anon_sym_LT,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_int,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [1857] = 2,
    ACTIONS(163), 4,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_fn,
    ACTIONS(161), 7,
      anon_sym_LPAREN,
      anon_sym_LT,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_int,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [1873] = 3,
    ACTIONS(165), 1,
      anon_sym_COMMA,
    ACTIONS(167), 1,
      anon_sym_RBRACK,
    STATE(57), 1,
      aux_sym__vals_repeat1,
  [1883] = 3,
    ACTIONS(165), 1,
      anon_sym_COMMA,
    ACTIONS(169), 1,
      anon_sym_RBRACK,
    STATE(61), 1,
      aux_sym__vals_repeat1,
  [1893] = 3,
    ACTIONS(171), 1,
      anon_sym_RPAREN,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    STATE(62), 1,
      aux_sym_params_repeat1,
  [1903] = 3,
    ACTIONS(83), 1,
      anon_sym_COMMA,
    ACTIONS(175), 1,
      anon_sym_RPAREN,
    STATE(63), 1,
      aux_sym_args_repeat1,
  [1913] = 3,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    ACTIONS(177), 1,
      anon_sym_RPAREN,
    STATE(58), 1,
      aux_sym_params_repeat1,
  [1923] = 3,
    ACTIONS(179), 1,
      anon_sym_COMMA,
    ACTIONS(182), 1,
      anon_sym_RBRACK,
    STATE(61), 1,
      aux_sym__vals_repeat1,
  [1933] = 3,
    ACTIONS(184), 1,
      anon_sym_RPAREN,
    ACTIONS(186), 1,
      anon_sym_COMMA,
    STATE(62), 1,
      aux_sym_params_repeat1,
  [1943] = 3,
    ACTIONS(95), 1,
      anon_sym_RPAREN,
    ACTIONS(189), 1,
      anon_sym_COMMA,
    STATE(63), 1,
      aux_sym_args_repeat1,
  [1953] = 3,
    ACTIONS(192), 1,
      anon_sym_RPAREN,
    ACTIONS(194), 1,
      sym_identifier,
    STATE(74), 1,
      sym_params,
  [1963] = 1,
    ACTIONS(182), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1968] = 1,
    ACTIONS(184), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1973] = 1,
    ACTIONS(196), 1,
      anon_sym_SEMI,
  [1977] = 1,
    ACTIONS(198), 1,
      sym_identifier,
  [1981] = 1,
    ACTIONS(200), 1,
      ts_builtin_sym_end,
  [1985] = 1,
    ACTIONS(202), 1,
      anon_sym_LPAREN,
  [1989] = 1,
    ACTIONS(204), 1,
      anon_sym_RBRACE,
  [1993] = 1,
    ACTIONS(206), 1,
      anon_sym_RPAREN,
  [1997] = 1,
    ACTIONS(208), 1,
      anon_sym_DQUOTE,
  [2001] = 1,
    ACTIONS(210), 1,
      anon_sym_RPAREN,
  [2005] = 1,
    ACTIONS(212), 1,
      sym__string,
  [2009] = 1,
    ACTIONS(214), 1,
      anon_sym_RBRACK,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 63,
  [SMALL_STATE(7)] = 125,
  [SMALL_STATE(8)] = 187,
  [SMALL_STATE(9)] = 249,
  [SMALL_STATE(10)] = 305,
  [SMALL_STATE(11)] = 361,
  [SMALL_STATE(12)] = 417,
  [SMALL_STATE(13)] = 473,
  [SMALL_STATE(14)] = 529,
  [SMALL_STATE(15)] = 585,
  [SMALL_STATE(16)] = 641,
  [SMALL_STATE(17)] = 697,
  [SMALL_STATE(18)] = 753,
  [SMALL_STATE(19)] = 809,
  [SMALL_STATE(20)] = 844,
  [SMALL_STATE(21)] = 881,
  [SMALL_STATE(22)] = 920,
  [SMALL_STATE(23)] = 961,
  [SMALL_STATE(24)] = 1006,
  [SMALL_STATE(25)] = 1051,
  [SMALL_STATE(26)] = 1094,
  [SMALL_STATE(27)] = 1140,
  [SMALL_STATE(28)] = 1161,
  [SMALL_STATE(29)] = 1182,
  [SMALL_STATE(30)] = 1225,
  [SMALL_STATE(31)] = 1246,
  [SMALL_STATE(32)] = 1287,
  [SMALL_STATE(33)] = 1308,
  [SMALL_STATE(34)] = 1351,
  [SMALL_STATE(35)] = 1372,
  [SMALL_STATE(36)] = 1393,
  [SMALL_STATE(37)] = 1414,
  [SMALL_STATE(38)] = 1435,
  [SMALL_STATE(39)] = 1456,
  [SMALL_STATE(40)] = 1477,
  [SMALL_STATE(41)] = 1498,
  [SMALL_STATE(42)] = 1519,
  [SMALL_STATE(43)] = 1559,
  [SMALL_STATE(44)] = 1599,
  [SMALL_STATE(45)] = 1639,
  [SMALL_STATE(46)] = 1679,
  [SMALL_STATE(47)] = 1699,
  [SMALL_STATE(48)] = 1732,
  [SMALL_STATE(49)] = 1759,
  [SMALL_STATE(50)] = 1776,
  [SMALL_STATE(51)] = 1793,
  [SMALL_STATE(52)] = 1809,
  [SMALL_STATE(53)] = 1825,
  [SMALL_STATE(54)] = 1841,
  [SMALL_STATE(55)] = 1857,
  [SMALL_STATE(56)] = 1873,
  [SMALL_STATE(57)] = 1883,
  [SMALL_STATE(58)] = 1893,
  [SMALL_STATE(59)] = 1903,
  [SMALL_STATE(60)] = 1913,
  [SMALL_STATE(61)] = 1923,
  [SMALL_STATE(62)] = 1933,
  [SMALL_STATE(63)] = 1943,
  [SMALL_STATE(64)] = 1953,
  [SMALL_STATE(65)] = 1963,
  [SMALL_STATE(66)] = 1968,
  [SMALL_STATE(67)] = 1973,
  [SMALL_STATE(68)] = 1977,
  [SMALL_STATE(69)] = 1981,
  [SMALL_STATE(70)] = 1985,
  [SMALL_STATE(71)] = 1989,
  [SMALL_STATE(72)] = 1993,
  [SMALL_STATE(73)] = 1997,
  [SMALL_STATE(74)] = 2001,
  [SMALL_STATE(75)] = 2005,
  [SMALL_STATE(76)] = 2009,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__binexp35, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__binexp25, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__binexp15, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__binexp5, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unexp, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cond, 5, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_args, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__def_braces, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_args_repeat1, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 5, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__def_braces, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 4, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exp, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binexp, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 2, 0, 1),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 2, 0, 1),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binop15, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binop15, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unop, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unop, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binop35, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binop35, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binop25, 1, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binop25, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binop5, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binop5, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__vals, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__vals, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_args, 2, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 1, 0, 0),
  [179] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__vals_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__vals_repeat1, 2, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2, 0, 0),
  [186] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [189] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_args_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [200] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_saf(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
